# @name get-prompts

GET http://localhost:3333/prompts

### 
# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exampleg1.mp3"
Content-Type: audio/mpeg

< ./exampleg1.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name create-transcription

POST http://localhost:3333/videos/be106b47-228a-49e8-b18c-d25583bfbe55/transcription
Content-Type: application/json

{
  "prompt": "g1, preso"
}

###
# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "be106b47-228a-49e8-b18c-d25583bfbe55",
  "temperature": 0.5,
  "prompt": "gere um resumo da trascrição do video: '''{transcription}'''"
}

